# Generated by Django 3.2.16 on 2022-10-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='value',
            new_name='amount',
        ),
    ]
